"""Shared fixtures and helpers for the extraction test suite.

All tests run against the committed synthetic archives in
fixtures/archives/ — never against real personal data. Those archives
are generated by `python -m fixtures.generate_fixtures --seed 42` and
committed deliberately, so the tests and the canary assert against a
fixed, reviewable set of bytes rather than whatever a fresh generator
run happens to produce.
"""

from __future__ import annotations

import zipfile
from pathlib import Path

import pytest

from port.donation.schema import DonationRecord

ARCHIVES = Path(__file__).resolve().parent.parent / "fixtures" / "archives"


@pytest.fixture(scope="session")
def archives() -> Path:
    return ARCHIVES


def archive(relative: str) -> Path:
    """Resolve a fixture archive path, failing loudly if it's missing.

    A missing archive means the fixtures weren't regenerated (or were
    dropped from the commit) — a plain FileNotFoundError deep inside
    zipfile is a confusing way to discover that.
    """
    path = ARCHIVES / relative
    if not path.exists():
        raise AssertionError(
            f"Fixture archive not found: {path}\n"
            "Regenerate with: poetry run python -m fixtures.generate_fixtures --seed 42"
        )
    return path


def extract(extractor, relative: str, locale: str = "en") -> list[DonationRecord]:
    """Run an extractor against a named fixture archive."""
    with zipfile.ZipFile(archive(relative)) as zf:
        return extractor(zf, locale)


def counts_by_type(records: list[DonationRecord]) -> dict[str, int]:
    out: dict[str, int] = {}
    for r in records:
        out[r.record_type] = out.get(r.record_type, 0) + 1
    return out


def fill_rate(records: list[DonationRecord], field: str) -> float:
    """Share of records where `field` is populated (not None).

    The canary's core metric. Record *count* alone can't detect a
    platform renaming a field: the row count stays identical while
    every value silently becomes None. Fill rate catches exactly that.
    """
    if not records:
        return 0.0
    return sum(1 for r in records if getattr(r, field) is not None) / len(records)
